//firebase_options.dart
// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFsLwC4zjAtUxjflP1Z2w3Hn_GTZ42vmA',
    appId: '1:328954332946:web:893e29f47c43c2738915cb',
    messagingSenderId: '328954332946',
    projectId: 'flutter-lab-project-4a99e',
    authDomain: 'flutter-lab-project-4a99e.firebaseapp.com',
    storageBucket: 'flutter-lab-project-4a99e.firebasestorage.app',
    measurementId: 'G-HFTJQJXQXN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTLLRsaQP7nn6Jso_Jg8JEtPDwvtcsbRU',
    appId: '1:328954332946:android:73218e02775e4c848915cb',
    messagingSenderId: '328954332946',
    projectId: 'flutter-lab-project-4a99e',
    storageBucket: 'flutter-lab-project-4a99e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBh9ur6V1l50pKDZP2Z00d2WBy1C7lmlUY',
    appId: '1:328954332946:ios:96acab26b843ccaa8915cb',
    messagingSenderId: '328954332946',
    projectId: 'flutter-lab-project-4a99e',
    storageBucket: 'flutter-lab-project-4a99e.firebasestorage.app',
    iosBundleId: 'com.example.flutterLabProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBh9ur6V1l50pKDZP2Z00d2WBy1C7lmlUY',
    appId: '1:328954332946:ios:96acab26b843ccaa8915cb',
    messagingSenderId: '328954332946',
    projectId: 'flutter-lab-project-4a99e',
    storageBucket: 'flutter-lab-project-4a99e.firebasestorage.app',
    iosBundleId: 'com.example.flutterLabProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCFsLwC4zjAtUxjflP1Z2w3Hn_GTZ42vmA',
    appId: '1:328954332946:web:a9597406368764588915cb',
    messagingSenderId: '328954332946',
    projectId: 'flutter-lab-project-4a99e',
    authDomain: 'flutter-lab-project-4a99e.firebaseapp.com',
    storageBucket: 'flutter-lab-project-4a99e.firebasestorage.app',
    measurementId: 'G-STXX39L3VZ',
  );
}
